#!/usr/bin/env bash

NAME="rpm-builder-waf"
TAG="${NAME}:${BUILD_NUMBER:-1}"
CONTAINER_NAME="${NAME}-build-${BUILD_NUMBER:-1}"


TEMP_EXTENSION=tmp-$CONTAINER_NAME-$(date +"%s")
SHARED_TEMP_HOST=$SHARED_JENKINS_PATH_HOST/$TEMP_EXTENSION
SHARED_TEMP_CONTAINER=$SHARED_JENKINS_PATH_CONTAINER/$TEMP_EXTENSION

SHARED_JENKINS_PATH_HOST

if [ ! -f $SHARED_TEMP_CONTAINER ]; then
    mkdir -p $SHARED_TEMP_CONTAINER
fi

sudo docker build -t $TAG . && \
sudo docker run \
    --name=$CONTAINER_NAME \
    -e "RPM_OUTPUT_DIR=/rpms" \
    -v "$SHARED_TEMP_HOST:/rpms" \
    $TAG && \
sudo docker rm $CONTAINER_NAME

cp $SHARED_TEMP_CONTAINER/* $(pwd)
rm -rf $SHARED_TEMP_CONTAINER
